package com.lamndt.smartmovie.multiplatform.model

enum class AppLocale(val tag: String, val backendTag: String, val nativeName: String) {
    ENGLISH("en", "en-US", "English"),
    VIETNAMESE("vi", "vi-VN", "Tiếng Việt"),
    JAPANESE("ja", "ja-JP", "日本語"),
    KOREAN("ko", "ko-KR", "한국어"),
    CHINESE_SIMPLIFIED("zh-CN", "zh-CN", "简体中文"),
    CHINESE_TRADITIONAL("zh-TW", "zh-TW", "繁體中文");

    companion object {
        fun fromTag(value: String?): AppLocale = entries.firstOrNull {
            it.tag.equals(value, ignoreCase = true) || it.backendTag.equals(value, ignoreCase = true)
        } ?: ENGLISH
    }
}

data class UiStrings(
    val home: String,
    val explore: String,
    val search: String,
    val library: String,
    val profile: String,
    val movies: String,
    val tvSeries: String,
    val discover: String,
    val searchHint: String,
    val catalog: String,
    val externalId: String,
    val findMatches: String,
    val searchByExternalId: String,
    val externalIdHint: String,
    val tryAnotherExternalId: String,
    val all: String,
    val favorites: String,
    val watchlist: String,
    val favorite: String,
    val watchLater: String,
    val removeFavorite: String,
    val removeWatchlist: String,
    val trailer: String,
    val details: String,
    val story: String,
    val cast: String,
    val similar: String,
    val rating: String,
    val year: String,
    val sort: String,
    val popularity: String,
    val topRated: String,
    val releaseDate: String,
    val reset: String,
    val retry: String,
    val loading: String,
    val noResults: String,
    val emptyLibrary: String,
    val serviceError: String,
    val language: String,
    val platformEdition: String,
    val loadMore: String,
    val close: String,
    val creditDetails: String,
    val person: String,
    val role: String,
    val character: String,
    val job: String,
    val department: String,
    val crew: String,
    val guestStars: String,
    val creditTitle: String,
    val advancedDiscover: AdvancedDiscoverStrings,
)

data class AdvancedDiscoverStrings(
    val filters: String,
    val releaseRange: String,
    val dateFrom: String,
    val dateThrough: String,
    val originalLanguage: String,
    val originCountry: String,
    val certification: String,
    val minimum: String,
    val maximum: String,
    val runtimeAndVotes: String,
    val minimumRuntime: String,
    val maximumRuntime: String,
    val minimumVoteCount: String,
    val watchProviders: String,
    val region: String,
    val providersUnavailable: String,
    val availability: String,
    val subscription: String,
    val free: String,
    val withAds: String,
    val rent: String,
    val buy: String,
    val apply: String,
    val any: String,
    val justWatch: String,
)

fun strings(locale: AppLocale): UiStrings = when (locale) {
    AppLocale.ENGLISH -> UiStrings(
        "Home", "Explore", "Search", "Library", "Profile", "Movies", "TV Series", "Discover",
        "Search titles, people, collections, companies and keywords",
        "Catalog", "External ID", "Find matches", "Search by external ID",
        "Enter an ID from another database and choose its source", "Try a different ID or source",
        "All", "Favorites", "Watchlist", "Favorite", "Watch later",
        "Remove favorite", "Remove from watchlist", "Play trailer", "View details", "Story", "Cast",
        "Similar titles", "Rating", "Year", "Sort", "Popularity", "Top rated", "Release date", "Reset",
        "Try again", "Loading…", "No titles found", "Your library is ready for its first title",
        "SmartMovie could not reach the catalog", "Language", "Multiplatform edition", "Load more", "Close",
        "Credit details", "Person", "Role", "Character", "Job", "Department", "Crew", "Guest stars", "Title",
        AdvancedDiscoverStrings(
            "Advanced filters", "Release date range", "From (YYYY-MM-DD)", "Through (YYYY-MM-DD)",
            "Original language (ISO)", "Origin country (ISO)", "Certification", "Minimum", "Maximum",
            "Runtime and votes", "Minimum minutes", "Maximum minutes", "Minimum vote count", "Watch providers",
            "Region", "No providers are available for this region.", "Availability", "Streaming", "Free",
            "With ads", "Rent", "Buy", "Apply filters", "Any", "Availability data by JustWatch",
        ),
    )
    AppLocale.VIETNAMESE -> UiStrings(
        "Trang chủ", "Khám phá", "Tìm kiếm", "Thư viện", "Hồ sơ", "Phim điện ảnh", "Phim bộ", "Khám phá",
        "Tìm phim, con người, bộ sưu tập, công ty và từ khóa",
        "Danh mục", "ID bên ngoài", "Tìm kết quả", "Tìm bằng ID bên ngoài",
        "Nhập ID từ cơ sở dữ liệu khác và chọn nguồn tương ứng", "Hãy thử ID hoặc nguồn khác",
        "Tất cả", "Yêu thích", "Xem sau", "Yêu thích", "Xem sau",
        "Bỏ yêu thích", "Bỏ khỏi xem sau", "Xem trailer", "Xem chi tiết", "Câu chuyện", "Diễn viên",
        "Tựa phim tương tự", "Điểm", "Năm", "Sắp xếp", "Phổ biến", "Đánh giá cao", "Ngày phát hành", "Đặt lại",
        "Thử lại", "Đang tải…", "Không tìm thấy tựa phim", "Thư viện đang chờ tựa phim đầu tiên",
        "SmartMovie không thể kết nối danh mục", "Ngôn ngữ", "Phiên bản đa nền tảng", "Tải thêm", "Đóng",
        "Chi tiết vai diễn", "Người", "Vai trò", "Nhân vật", "Công việc", "Bộ phận", "Đoàn làm phim", "Diễn viên khách mời", "Tựa phim",
        AdvancedDiscoverStrings(
            "Bộ lọc nâng cao", "Khoảng ngày phát hành", "Từ ngày (YYYY-MM-DD)", "Đến ngày (YYYY-MM-DD)",
            "Ngôn ngữ gốc (ISO)", "Quốc gia sản xuất (ISO)", "Phân loại độ tuổi", "Tối thiểu", "Tối đa",
            "Thời lượng và lượt đánh giá", "Số phút tối thiểu", "Số phút tối đa", "Lượt đánh giá tối thiểu", "Nhà cung cấp nội dung",
            "Khu vực", "Không có nhà cung cấp cho khu vực này.", "Hình thức xem", "Thuê bao", "Miễn phí",
            "Có quảng cáo", "Thuê", "Mua", "Áp dụng bộ lọc", "Bất kỳ", "Dữ liệu nơi xem do JustWatch cung cấp",
        ),
    )
    AppLocale.JAPANESE -> UiStrings(
        "ホーム", "見つける", "検索", "ライブラリ", "プロフィール", "映画", "テレビ", "作品を探す",
        "作品、人物、コレクション、会社、キーワードを検索",
        "カタログ", "外部ID", "一致を検索", "外部IDで検索",
        "別のデータベースのIDを入力し、ソースを選択してください", "別のIDまたはソースをお試しください",
        "すべて", "お気に入り", "ウォッチリスト", "お気に入り", "後で見る",
        "お気に入りを解除", "リストから削除", "予告編を再生", "詳細を見る", "ストーリー", "キャスト",
        "関連作品", "評価", "年", "並び替え", "人気順", "高評価", "公開日", "リセット",
        "再試行", "読み込み中…", "作品が見つかりません", "最初の作品をライブラリに追加しましょう",
        "カタログに接続できません", "言語", "マルチプラットフォーム版", "さらに読み込む", "閉じる",
        "クレジット詳細", "人物", "役割", "役名", "担当", "部門", "スタッフ", "ゲスト出演", "作品",
        AdvancedDiscoverStrings(
            "詳細フィルター", "公開日の範囲", "開始日 (YYYY-MM-DD)", "終了日 (YYYY-MM-DD)",
            "原語 (ISO)", "製作国 (ISO)", "年齢区分", "最小", "最大", "上映時間と投票数", "最短（分）",
            "最長（分）", "最小投票数", "配信サービス", "地域", "この地域で利用できる配信サービスはありません。",
            "視聴方法", "定額配信", "無料", "広告付き", "レンタル", "購入", "フィルターを適用", "指定なし", "配信情報はJustWatch提供",
        ),
    )
    AppLocale.KOREAN -> UiStrings(
        "홈", "둘러보기", "검색", "라이브러리", "프로필", "영화", "TV 시리즈", "작품 찾기",
        "작품, 인물, 컬렉션, 회사 및 키워드 검색",
        "카탈로그", "외부 ID", "일치 항목 찾기", "외부 ID로 검색",
        "다른 데이터베이스의 ID를 입력하고 출처를 선택하세요", "다른 ID 또는 출처를 시도해 보세요",
        "전체", "즐겨찾기", "관심 목록", "즐겨찾기", "나중에 보기",
        "즐겨찾기 해제", "관심 목록에서 삭제", "예고편 재생", "상세 보기", "줄거리", "출연진",
        "비슷한 작품", "평점", "연도", "정렬", "인기순", "평점순", "공개일", "초기화",
        "다시 시도", "불러오는 중…", "작품을 찾을 수 없습니다", "첫 작품을 라이브러리에 추가해 보세요",
        "카탈로그에 연결할 수 없습니다", "언어", "멀티플랫폼 에디션", "더 불러오기", "닫기",
        "크레딧 상세", "인물", "역할", "배역", "직무", "부서", "제작진", "게스트 출연", "작품",
        AdvancedDiscoverStrings(
            "고급 필터", "공개일 범위", "시작일 (YYYY-MM-DD)", "종료일 (YYYY-MM-DD)", "원어 (ISO)",
            "제작 국가 (ISO)", "시청 등급", "최소", "최대", "상영 시간 및 투표 수", "최소 시간(분)", "최대 시간(분)",
            "최소 투표 수", "시청 제공자", "지역", "이 지역에서 이용 가능한 제공자가 없습니다.", "이용 유형",
            "구독", "무료", "광고 포함", "대여", "구매", "필터 적용", "전체", "JustWatch 제공 시청 가능 정보",
        ),
    )
    AppLocale.CHINESE_SIMPLIFIED -> UiStrings(
        "首页", "探索", "搜索", "片库", "个人资料", "电影", "剧集", "发现作品",
        "搜索作品、人物、合集、公司和关键词",
        "目录", "外部 ID", "查找匹配项", "按外部 ID 搜索",
        "输入其他数据库中的 ID，并选择其来源", "请尝试其他 ID 或来源",
        "全部", "收藏", "想看", "收藏", "稍后观看",
        "取消收藏", "移出想看", "播放预告", "查看详情", "剧情", "演员",
        "相似作品", "评分", "年份", "排序", "热门", "高分", "上映日期", "重置",
        "重试", "加载中…", "未找到作品", "把第一部作品加入片库吧",
        "SmartMovie 无法连接目录", "语言", "多平台版本", "加载更多", "关闭",
        "演职员详情", "人物", "角色", "饰演", "职务", "部门", "幕后人员", "客串演员", "作品",
        AdvancedDiscoverStrings(
            "高级筛选", "上映日期范围", "开始日期 (YYYY-MM-DD)", "结束日期 (YYYY-MM-DD)", "原始语言 (ISO)",
            "制作国家/地区 (ISO)", "分级", "最低", "最高", "片长与投票数", "最短分钟数", "最长分钟数", "最少投票数",
            "观看平台", "地区", "此地区没有可用平台。", "观看方式", "订阅", "免费", "含广告", "租赁", "购买",
            "应用筛选", "不限", "可观看信息由 JustWatch 提供",
        ),
    )
    AppLocale.CHINESE_TRADITIONAL -> UiStrings(
        "首頁", "探索", "搜尋", "片庫", "個人資料", "電影", "影集", "探索作品",
        "搜尋作品、人物、合輯、公司和關鍵字",
        "目錄", "外部 ID", "尋找符合項目", "依外部 ID 搜尋",
        "輸入其他資料庫中的 ID，並選擇其來源", "請嘗試其他 ID 或來源",
        "全部", "收藏", "待看清單", "收藏", "稍後觀看",
        "取消收藏", "移出待看", "播放預告", "查看詳情", "故事", "演員",
        "相似作品", "評分", "年份", "排序", "熱門", "高評分", "上映日期", "重設",
        "再試一次", "載入中…", "找不到作品", "將第一部作品加入片庫吧",
        "SmartMovie 無法連線至目錄", "語言", "多平台版本", "載入更多", "關閉",
        "演職員詳情", "人物", "角色", "飾演", "職務", "部門", "幕後人員", "客串演員", "作品",
        AdvancedDiscoverStrings(
            "進階篩選", "上映日期範圍", "開始日期 (YYYY-MM-DD)", "結束日期 (YYYY-MM-DD)", "原始語言 (ISO)",
            "製作國家/地區 (ISO)", "分級", "最低", "最高", "片長與投票數", "最短分鐘數", "最長分鐘數", "最少投票數",
            "觀看平台", "地區", "此地區沒有可用平台。", "觀看方式", "訂閱", "免費", "含廣告", "租借", "購買",
            "套用篩選", "不限", "可觀看資訊由 JustWatch 提供",
        ),
    )
}
